# add new row to dimentoin table as "Not Specified"
NotSpecifiedRow = Table.InsertRows(
Source,
1,{
    [
        BranchID  = "Not Specified",
        BranchName = "Not Specified",
        BranchLocation= "Not Specified",
         NameOfBusiness = "Not Specified"
         ...... = .......
        ]
}
-----------------------------------------
Change all columns to ProperCase and remove ugly  _s 

HeadersProperCase = Table.TransformColumnNames(Source,Text.Proper),
RenameColumns = Table.RenameColumns(HeadersProperCase, Table.ToRows(Table.AddColumn(Table.FromList(Table.ColumnNames( HeadersProperCase)),
"New Column Name", each Text.Replace ( [Column1] , "_" , " " ))))
in
    RenameColumns
