# add new row to dimentoin table as "Not Specified"
NotSpecifiedRow = Table.InsertRows(
Source,
1,{
    [
        BranchID  = "Not Specified",
        BranchName = "Not Specified",
        BranchLocation= "Not Specified",
         NameOfBusiness = "Not Specified"
         ...... = .......
        ]
}
-----------------------------------------
Change all columns to ProperCase and remove ugly Characters 

, 
  #"Beautiful Columns Names" = Table.TransformColumnNames(Source, Text.Proper), 
  #"Remove Ugly Characters!" = Table.RenameColumns(
    #"Beautiful Columns Names", 
    Table.ToRows(
      Table.AddColumn(
        Table.FromList(Table.ColumnNames(#"Beautiful Columns Names")), 
        "New Column Name", 
        each Text.Replace([Column1], "_", " ")
      )
    )
  )
in
  #"Remove Ugly Characters!"
  
  ------------------------------------------------------
  # Flag if the column  has letter values of Not
  Text.Length(Text.Select([Column1],{"A".."Z"}))>0  
-------------------------------------------------------
# Adding a Static Table with Types in Power Query With M Language
https://sergiomurru.com/2021/02/08/adding-a-static-table-with-types-in-power-query-with-m-language/
The M code to create the Segments table is the following
#table(
    type table
        [
            #"Price Range"=text, 
            #"Min Price"=number,
            #"Max Price"=number
        ], 
    {
        {"LOW", 0, 100},
        {"MEDIUM", 100, 1000},
        {"HIGH", 1000, 999999}
    }
)
