# add new row to dimentoin table as "Not Specified"
NotSpecifiedRow = Table.InsertRows(
Source,
1,{
    [
        BranchID  = "Not Specified",
        BranchName = "Not Specified",
        BranchLocation= "Not Specified",
         NameOfBusiness = "Not Specified"
         ...... = .......
        ]
}
-----------------------------------------
Change all columns to ProperCase and remove ugly Characters 

, 
  #"Beautiful Columns Names" = Table.TransformColumnNames(Source, Text.Proper), 
  #"Remove Ugly Characters!" = Table.RenameColumns(
    #"Beautiful Columns Names", 
    Table.ToRows(
      Table.AddColumn(
        Table.FromList(Table.ColumnNames(#"Beautiful Columns Names")), 
        "New Column Name", 
        each Text.Replace([Column1], "_", " ")
      )
    )
  )
in
  #"Remove Ugly Characters!"
  
  ------------------------------------------------------
  ## Flag if the column  has letter values of Not
  Text.Length(Text.Select([Column1],{"A".."Z"}))>0  
-------------------------------------------------------

